# /etc/rsyncd.conf

# Global settings
uid = 0
gid = 0
use chroot = no
max connections = 4
log file = /var/log/rsync.log
pid file = /var/run/rsyncd.pid
port = 873

# Define a module called "workspace"
[workspace]
    path = /workspace
    read only = false
    list = yes
